---
author: Reza Amiri, BA, MSc, PhD
date: '2021-10-26'
title: An Introduction to Meta-Analysis with R
output:
  html_document:
    number_sections: true
    toc: true
    toc_depth: 2.0
toc-title: "Outline"
fontsize: 10pt
citecolor: blue
urlcolor: red
bibliography: references.bib
biblio-title: References
csl: apa.csl
link-citations: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Making Everything Ready

Visit this [link](https://learnr-examples.shinyapps.io/ex-setup-r/ "To setup R, RStudio IDE, and guide to install packages") to find out how to install R, RStudio IDE, and install R packages.

## R

R is a free software environment for statistical computing and graphics. R software can be downloaded [here](https://www.r-project.org/). The most recent version of R is 4.1.1 (Kick Things) and has been released on 2021-08-10. However, some packages that I frequently use do not support the newest version of R. Facilitating this issue, I use version 3.6.3 on my system.

Nonetheless, you are able to install and use multiple version of R on your system and using RStudio you can switch back and forth to any version of R based on your needs.

To get help using R access their webpage [here](https://www.r-project.org/help.html).

## RStudio

RStudio's mission is to create free and open-source software for data science, scientific research, and technical communication. Inspired by innovators in science, education, government, and industry, RStudio develops free and open tools for R, and enterprise-ready professional products for teams who use both R and Python, to scale and share their work. RStudio Integrated development environment (IDE) can be downloaded [here](https://www.rstudio.com/products/rstudio/download/). We are using RStudio for this workshop.

# What is a meta-analysis (MA)?

## Definition

The definition by one of its founding father:

> "Analysis of analyses" [@glass1976]

> "Meta-analysis can be understood as a form of survey research in which research reports, rather than people, are surveyed." [@lipsey2001]

# Best packages to conduct a MA

The best packages are:

# Data Preparation

# Hands-on practice

Some text

# References
